; 拷贝笔记, 常用于子笔记分享，不想分享整个笔记本的情况下，
; 自动把资源收集存放到新目录用于后续打包分享
[copy_obsidian_note]
mdfile = "DDR3"
srcdir = "E:/project/notebook/obsidian-notebook/软件开发/05-drivers/方向：高速接口/ZYNQPL快速学习"
dstdir = "E:/project/testshare"
vault_root = "E:/project/notebook/obsidian-notebook"
backup = False


; 转移笔记, 常用于在 Obsidian vault 范围内，对笔记进行挪位置
; [migrate_obsidian_note]
; mdfile = "zynq-axi-dma.md"
; srcdir = "E:/xxx"
; dstdir = "E:/yyy"
; backup = True